Feature restaurante
Firmastech/firmas-food pull request #6
Opened 2024-07-13 17:46 UTC by RenanJar

Adiciona duas novas funcionalidades na aplicação : 
--Criar Restaurante
--Consultar restaurante por ID

Adiciona manipulador de Exception ;

Remove Tabela Restaurante do script 

Adiciona novo Script responsavel por adicionar a Tabela de Restaurante

Adiciona dependência Junit5 ao projeto

Adiciona Classe Base de Entidade contendo os atributos de controle 

Corrige a referencia ao banco de dados: agora aponta para db_restaurante

2024-07-14 03:35 UTC, danieldjgomes requested changes
Avaliar as anotações.

2024-07-14 03:35 UTC, danieldjgomes commented on src/main/java/danieldjgomes/larica/dataprovider/repository/RestauranteMapper.java
> +    //@Mapping(target = "endereco", ignore = true)
Acho que você esqueceu de remover.

2024-07-14 03:35 UTC, danieldjgomes commented on src/main/java/danieldjgomes/larica/core/restaurante/entity/Restaurante.java
> +  public void validar(){
Eu não concordo em validar assim, eu acho que dentro do modelo puro o objeto já deva entrar validado numa camada anterior. Eu usaria o pacote Jakarta Validation  e usaria @Valid e @Validate para tratar isso nos controller invés de trazer isso para o modelo puro.

https://www.baeldung.com/java-validation

2024-07-14 03:35 UTC, danieldjgomes commented on src/main/java/danieldjgomes/larica/core/exceptions/ValidationException.java
> +        super(message);
Utilizar uma exceção para cada tipo de erro de validação

2024-07-14 03:35 UTC, danieldjgomes commented on src/main/java/danieldjgomes/larica/dataprovider/repository/entity/BaseEntity.java
> +    @Column(name = "ativo", nullable = false, length = 10)
Boolean com comprimento

2024-07-14 03:35 UTC, danieldjgomes commented on src/main/java/danieldjgomes/larica/dataprovider/repository/entity/RestauranteEntity.java
> +            columnDefinition = "varchar(36)")
Nao precisa do   columnDefinition

2024-07-14 03:35 UTC, danieldjgomes commented on src/main/java/danieldjgomes/larica/infrastructure/controller/ManipuladorGlobalDeErros.java
> +public class ManipuladorGlobalDeErros {
GlobalExceptionHandler por favor

2024-07-14 03:35 UTC, danieldjgomes commented on src/main/resources/sql/createRestaurantTable.sql
> +CREATE TABLE restaurante (
Junta no outro arquivo sql

2024-07-15 18:02 UTC, HenriqueLimaAlves approved these changes

2024-07-29 15:01 UTC, closed without merging